language: go
go:
  - 1.3
  - 1.4
  - tip
before_install:
  - mkdir -p $HOME/gopath/src/eriol.xyz
  - mv $TRAVIS_BUILD_DIR $HOME/gopath/src/eriol.xyz/perpetua
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/eriol.xyz/perpetua
  - cd $TRAVIS_BUILD_DIR
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
    - $HOME/gopath/bin/goveralls -v -service=travis-ci
