language: go
go:
  - 1.3
  - 1.4
  - tip
before_install:
  - mkdir -p $HOME/gopath/src/eriol.xyz
  - mv $TRAVIS_BUILD_DIR $HOME/gopath/src/eriol.xyz/perpetua
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/eriol.xyz/perpetua
  - cd $TRAVIS_BUILD_DIR
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get github.com/modocache/gover
script:
    - go test -coverprofile=config.coverprofile ./config
    - go test -coverprofile=db.coverprofile ./db
    - go test -coverprofile=irc.coverprofile ./irc
    - $HOME/gopath/bin/gover
    - $HOME/gopath/bin/goveralls -v -coverprofile=gover.coverprofile -service=travis-ci
